#  https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md
agent:
  podName: default
  customJenkinsLabels: default
  volumes:
    - type: PVC
      claimName: jenkins-agent
      mountPath: /home/jenkins
      readOnly: false

controller:
  numExecutors: 2
  additionalPlugins:
    - maven-plugin:3.23
    - pipeline-maven:1342.vfc697b_789147
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: admin
          name: admin
          password: admin
    configScripts:
      creds: |
        credentials:
          system:
            domainCredentials:
              - domain:
                  name: "github.com"
                  description: "GitHub domain"
                  specifications:
                    - hostnameSpecification:
                        includes: "github.com"
                credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github_credentials
                      username: vlad-lavrynovych
                      password: vlad300820001@gmail.com
                  - usernamePassword:
                      scope: GLOBAL
                      id: docker-hub-credentials
                      username: vlavrynovych
                      password: nikitos007
tool:
  maven:
    installations:
      - name: maven3
        home: "/maven3"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.4"
