#  https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md
agent:
  podName: default
  customJenkinsLabels: default
  volumes:
    - type: PVC
      claimName: jenkins-agent
      mountPath: /home/jenkins
      readOnly: false
controller:
  image: jenkins/jenkins
  tagLabel: jdk17
  installPlugins:
    - blueocean:1.27.8
    - kubernetes:4029.v5712230ccb_f8
    - workflow-aggregator:596.v8c21c963d92d
    - configuration-as-code:1670.v564dc8b_982d0
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: admin
          name: admin
          password: admin
    configScripts:
      creds: |
        credentials:
          system:
            domainCredentials:
              - domain:
                  name: "github.com"
                  description: "GitHub domain"
                  specifications:
                    - hostnameSpecification:
                        includes: "github.com"
                credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github_credentials
                      username: vlad-lavrynovych
                      password: vlad300820001@gmail.com
                  - usernamePassword:
                      scope: GLOBAL
                      id: docker-hub-credentials
                      username: vlavrynovych
                      password: nikitos007
tool:
  maven:
    installations:
      - name: "m3"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.6.2"