# Example values.yaml for Jenkins Helm Chart

# Jenkins master configuration
controller:
  name: jenkins-master  # Name of the Jenkins master Kubernetes StatefulSet

# Set the Jenkins admin user and password
adminUser: admin
adminPassword: admin

# Define the number of Jenkins agents (slaves) to run
agent:
  enabled: true
  image: "jenkins/inbound-agent:4.3-9"  # Docker image for the Jenkins agent
  imagePullPolicy: "IfNotPresent"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

# Enable/disable Jenkins RBAC (Role-Based Access Control)
rbac:
  create: true

# Configure Jenkins plugins (install or remove plugins)
# Example to install the Git and Docker plugins
plugins:
  - name: git
    version: 4.8.1
  - name: docker-workflow
    version: 1.26

# Define the persistent storage for Jenkins data
persistence:
  enabled: true
  storageClass: "default"  # Storage class for PVC (change if needed)
  size: "10Gi"             # Size of the PVC

# Kubernetes Jenkins Agent configuration
# Allows Jenkins agents to dynamically provision pods in the cluster
kubernetes:
  enabled: true
  namespace: "jenkins"  # Namespace where agents will run
  label: "jenkins-agent"  # Label to identify Jenkins agents
  image: "jenkins/jnlp-agent:4.10-4"  # Jenkins agent Docker image
  cpu: "200m"
  memory: "256Mi"

# Ingress configuration to expose Jenkins externally (optional)
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  pathType: Prefix
  hosts:
    - jenkins.example.com
  tls:
    - secretName: jenkins-tls-secret
      hosts:
        - jenkins.example.com
